### PR TITLE
Function tests to reach 80% coverage

### LINKED ISSUE #50: Write basic test suite
Tidyqpcr [needs to have a test suite to be submitted to rOpenSci](https://devguide.ropensci.org/building.html#testing). This needs to be implemented with [`testthat`](https://r-pkgs.org/tests.html).

Key unit tests are the interesting/workhorse functions that calculate:
* `calculate_normvalue`
* `calculate_deltacq_bysampleid`
* `calculate_deltadeltacq_bytargetid`
* `calculate_efficiency`
* `calculate_efficiency_bytargetid`

Maybe also the creation and labeling functions?
* `create_blank_plate`
*`label_plate_rowcol`

Later can think about the other functions for curve data:
* `debaseline`
* `calculate_dydx_1`
* `calculate_drdt_plate`

(edited to reflect updated names from #62)

### PR DESCRIPTION
**Pull request by DimmestP**
I have now added a suite of tests to cover 79.72% of all lines of R code. The files covered are:
- calculate_efficiency
- plate_functions
- calculate_deltacq
- amp_melt_curve_functions

In addition, to these tests I have add a covr button in the README.md file to report on the current test coverage. I have also added a GitHub action to run R CMD Check on every pull request (in Ubuntu, Windows and MacOS environments). Closes #50 

Perhaps @seaaan could also look if they are free?

### CODE REVIEW

**Comment by ewallace** [comment]
This looks amazing. I will try to figure out how to review this soon, given that my laptop is under repair and I’m not sure how best to run R.

**Comment by ewallace** [comment]
I’ve managed to look at this from an RStudio server and overall it’s amazing. Great test coverage and lots of material. If it’s passing automated R CMD check that’s good enough for me.

I have suggestions for further improvement, that I think could be done fairly fast?

## 1. Explain the test data

I am finding it hard to understand the data in the tests, even though I am meant to know this code very well.
Could we describe in a comment what each plate plan and data means? For example:

`# This is a sample dataset with x samples and y reps, that we use for…`

Bonus points for having some lines to visualise the data??? Maybe???

## 2. Simplify names of things

There are a lot of yeast-specific names that aren’t helpful.
Users and developers don’t need to know about HSP104, mCherry, SSD1, WT, etc.

Could we replace those with minimally relevant names, e.g. 
- S1, S2, … or Sample1, Sample2, …
- T1, T2, … or Target1, Target2, …

## 3. Did you style the code?

If you didn’t already, could you check the code style with lintr or styler?

## 4. Make sure the code coverage button points to the main branch of tidyqpcr

## 5. Is there still scope to simplify?

Now we have good code coverage, is it possible to write even simpler unit tests for core capabilities of the function? E.G. with smallest-possible dataframes?

Or without a `+RT` column so that we don’t need a `filter(Type == “+RT”)` in a test.

**Comment by ewallace** [comment]
### 5. Update “news” in README.md to mention test data?

Also update from July 2021 to October 2021, when we merge this pull request.

**Comment by DimmestP** [comment]
I have address points 2 and 4. You have addressed the README news issue and I have added issues for points 1 and 2/5. I think the pull request can be completed now.

**Comment by seaaan** [comment]
Wow, nice job! Looks like a lot of work! I don't have time to go through
all of the changes, but I'm happy to look over specific files or changes if
you can point me to particular questions.

**Pull request merged**
