### PR TITLE
Restyle code

### PR DESCRIPTION
**Pull request by ewallace**
Restyle code to *mostly* conform to tidyverse style guide.

* code spacing, commas, etc, are fixed.
* functions avoid explicit `return` statements unless necessary for control flow
* function names are snake_case:
  - `est_efficiency_1` renamed to `est_efficiency`, gives warning if run on multiple TargetIDs
  - `est_efficiency` renamed to `est_efficiency_bytargetid` 
  - `getNormCq` renamed to `calculate_normcq`
  -  `normalizeqPCR` renamed to `calculate_deltacq_bysampleid`; normalizeqPCR retained as deprecated alias.
  - calculate deltacq functions put into separate `calculate_deltacq.R` file
  - `create_colkey_xdilutions_mRTNT_in24` replaced by `create_colkey_xdiln_2ctrl_in24` where x=4,6.
  - `getdRdTall` replaced by `calculate_drdt_plate`
  - `getdRdT` replaced by `calculate_dydx_1`
  - vignette code restyled with styler

This addresses #48, and one of @seaaan's comments on rOpenSci discussion: https://discuss.ropensci.org/.

### CODE REVIEW

**Comment by DimmestP** [comment]
I am not entirely sure about the argument for using CamelCase, I don't think we can say we are following the tidyverse style guide and immediately break one of the basic principles of using snake_case for user defined variables. Especially since we don't use the sample variable name any more.

Unsure why rowkey, colkey and their variants (rowkey8, colkey12 ect) don't seem to follow any of the style guidelines (not CamelCase or snake_case) .

I think we really need to ram home that the tibble variable names are in CamelCase. Maybe a bold red warning the first time we define a rowkey/colkey in the example platesetup.

Worried that SampleIDs isn't sufficiently different from SampleID, and the same for TargetIDs and TargetID. Users mistakenly put tibble(SampleIDs = SampleIDs) when defining colkey, leading to confusing errors. Perhaps more explicit variable names can help;
```r
SampleIDCategories <- c("drug", "control")
SampleIDExpand <- rep(SampleIDCategories, each = 3)
colkey <- tibble(SampleID = SampleIDExpand)
```

**Comment by ewallace** [comment]
Thanks!

Would you propose rewriting with *all* the user-defined variables snake_case, then? `sample_id`, `target_id`, 

And changing `colkey...` to, for example, `create_colkey_6_in_24`? Likewise `create_rowkey_8_in_16_plain`?

Maybe we could set up a poll on the lab slack channel for any points of uncertainty?

The point about `SampleIDs` vs `SampleID` came up in user interviews and is important. This is about what things are called in the vignettes, not in the core functionality, though.

Following the above logic, what about:
```
sample_id_levels <- c("drug", "control")
sample_id_vector <- rep(sample_id_levels, each = 3)
colkey <- tibble(sample_id = sample_id_vector)
```

**Comment by ewallace** [comment]
Discussion with @DimmestP, leading to conclusions
* indeed, make every other variable snake_case where possible
* keep `colkey` and `rowkey` as "nouns" to describe column key data frames, etc. So we will use `create_colkey_6_in_24`.
* remember to fix out-of-style abominations such as `Value.norm` in `calculate_deltacq`.
* rename `est_efficiency` to `calculate_efficiency`

**Comment by ewallace** [comment]
As of commit ee6d192, this branch has now attempted to make **all** function and variable names in snake_case.
* sample_id replaces SampleID
* target_id replaces TargetID
* prep_type replaces Type
* well, well_col, well_row, replace Well, WellC, WellR
* biol_rep, tech_rep, replace BioRep, TechRep 
* in raw data (melt amp functions): fluor_raw, fluor_base, fluor_signal replace Fluor, Base, Signal.
* calculate_efficiency_... replaces est_efficiency_...
* create_colkey_... and create_rowkey... names are more thoroughly snake_case
* in calculate_deltacq etc, value_norm replaces Value.norm etc.
* variable names in vignettes also snake case (condition, drug, temperature, etc)
* read_qpcr_data.R has convenience functions for reading lightcycler data.
* fixed the imports as suggested in #55, fixing #28, removing most R CMD check complaints.

Still some R CMD check complaints to fix, detailed in #56 .

It would be great to review and incorporate by 3rd July.

**Comment by ewallace** [comment]
@DimmestP when you need a distraction from other projects, would be great to have your feedback on this pr.

**Comment by DimmestP** [comment]
I'm happy overall. Just wondering why in the calculate_efficiency_bytargetid function the input dataframe is called cq_df but in the calculate_efficiency function called by calculate_efficiency_bytargetid the input dataframe is renamed cq_df_1? Also comparing calculate_deltacq_bysampleid and calculate_normcq, the input dataframes are the same. However, in the deltadeltacq branch you rename the calculate_normcq input dataframe to value_df, why?

**Comment by ewallace** [comment]
* `cq_df_1` is called that to emphasize that it is only for one target_id. So that `cq_df` has values for many primer sets, and `cq_df_1` in `calculate_efficiency` runs only on one target_id from that.
* `calculate_normvalue` uses `value_df` because it allows flexibility in specifiying the column name that is normalised. Conceptually it is more generic than just Cq, so the tibble is called `value_df`.

In both cases, if you propose a better set of names, we can change it.

**Comment by DimmestP** [comment]
I'm happy overall. Just wondering why in the calculate_efficiency_bytargetid function the input dataframe is called cq_df but in the calculate_efficiency function called by calculate_efficiency_bytargetid the input dataframe is renamed cq_df_1? Also comparing calculate_deltacq_bysampleid and calculate_normcq, the input dataframes are the same. However, in the deltadeltacq branch you rename the calculate_normcq input dataframe to value_df, why?

**Comment by ewallace** [comment]
Was that a deliberate repeat comment?

Please suggest changes, or recommend acceptance.

**Pull request merged**
